version: '3.8'

services:
  front:
    image: nginx:latest
    container_name: portfolio-frontend
    ports:
        - "80:80"
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./front/dist:/usr/share/nginx/html

  back:
    build: ./back
    container_name: portfolio-backend
    ports:
      - "5000:5000"
